# Source Network's codecov configuration file.

github_checks:
    annotations: true

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 65...100

  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project:
      default:
        target: auto
        threshold: 5% # allow this much decrease on project
        flags:
          - unit

    patch: true

    changes: false


comment:
  layout: "reach, diff, files"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  - "docs"
  - ".circleci"
  - ".github"
  - "build"
  - "**/*.graphql"
  - "**/*_test.go"
  - "**/*.md"
  - "**/*.txt"
  - "db/tests"
  - "licenses"
  - ".gitignore"
  - ".golangci.sourceinc.yaml"
  - "Makefile"
