style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/sourcenetwork/defradb
options:
  commits:
  filters:
    Type:
      - feat
      - fix
      - perf
      - refactor
  commit_groups:
    title_maps:
      feat: Features
      fix: Fixes
      tools: Tooling
      docs: Documentation
      perf: Performance
      refactor: Refactoring
      test: Testing
      ci: Continuous integration
    sort_by: Custom
    title_order:
      - feat
      - fix
      - tools
      - docs
      - perf
      - refactor
      - test
      - ci
      - chore
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGES
      - BREAKING CHANGE
