name: Build Dependencies Workflow

on:
  pull_request:

  push:
    tags:
      - v*
    branches:
      - master
      - develop

jobs:
  build-dependencies:
    name: Build dependencies job

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code into the directory
        uses: actions/checkout@v3

      - name: Setup Go environment explicitly
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
          check-latest: true

      - name: Build all dependencies
        run: make deps
