name: Code Test Coverage

on: [push]

jobs:
  code-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Generate coverage report
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          verbose: true
          # path_to_write_report: ./coverage/codecov_report.txt
          # directory: ./coverage/reports/
