name: Code Test Coverage

on: [push]

jobs:
  code-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          check-latest: true

      - name: Generate full test coverage report using go-acc
        run: make test:coverage-full

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage-full.txt
          flags: defra-tests
          name: codecov-umbrella
          verbose: true
          # path_to_write_report: ./coverage/codecov_report.txt
          # directory: ./coverage/reports/
