name: Detect Change Workflow

on:
  pull_request:

  push:
    tags:
      - v*
    branches:
      - master
      - develop

jobs:
  detect-change:
    name: Detect change job

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code into the directory
        uses: actions/checkout@v3

      - name: Setup Go environment explicitly
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"
          check-latest: true

      - name: Build dependencies
        run: |
          make deps:modules
          make deps:test

      # We need SSH Authorization because change detection needs use `ls-remote` like:
      #  git ls-remote git@github.com:sourcenetwork/defradb.git refs/heads/develop
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run detection for changes
        run: make test:changes

      ## Uncomment to enable ability to SSH into the runner.
      #- name: Setup upterm ssh session for debugging
      #  uses: lhotari/action-upterm@v1
      #  with:
      #    limit-access-to-actor: true
      #    limit-access-to-users: shahzadlone
