# Copyright 2023 Democratized Data Foundation
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.

# This workflow validates that the images pushed to the container
# registries can be pulled then run sucessfully.
name: Pull Docker Image Workflow

on:
  workflow_run:
    # Warning: this workflow must NOT:
    # - interact with any new code.
    # - checkout new code.
    # - build/compile anything (only pull).
    # - make any indirect calls (i.e. make xyz, or npm install, etc.)
    # Note this workflow:
    # - will use the base's (or default) workflow file's state.
    # - doesn't run on the PR or the branch coming in, it runs on the default branch.
    # - has read-write repo token
    # - has access to secrets
    workflows: ["Push Docker Image To Registries Workflow"]
    types:
      - completed

jobs:
  pull-docker-image:
    name: Pull docker image job

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image_tag:
          - sourcenetwork/defradb:latest
          - ghcr.io/sourcenetwork/defradb:latest

    steps:
      - name: Pull Docker image
        run: docker pull ${{ matrix.image_tag }}

      - name: Test Docker image
        run: docker run --rm ${{ matrix.image_tag }}
