# Copyright 2023 Democratized Data Foundation
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.

# This workflow builds a Docker container image, if the build is successful
# then it will deploy the image to DockerHub & GitHub container registries.
name: Push Docker Image To Registries Workflow

on:
  pull_request:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  TEST_TAG: sourcenetwork/defradb:test

jobs:
  push-to-registries:
    name: Push Docker image to registries job
    
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: tools/defradb.containerfile
          platforms: linux/amd64,linux/arm64
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test Docker linux/amd64 image
        run: docker run --rm --platform linux/amd64 ${{ env.TEST_TAG }}

      - name: Test Docker linux/arm64 image
        run: docker run --rm --platform linux/arm64 ${{ env.TEST_TAG }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            sourcenetwork/defradb
            ghcr.io/${{ github.repository }}
      
      - name: Push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: tools/defradb.containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
